### ISSUE TITLE
Integrate tika-similarity as an ImageSpace plugin

### ISSUE THREAD

**Issue by harsham05** [memex-explorer/image_space#116]
Dear @danlamanna @jeffbaumes @chrismattmann @wmburke 

I am working on integrating [tika-similarity](https://github.com/chrismattmann/tika-similarity) into ImageSpace as a plugin, leveraging rich Solr Cores instead of files

Thank you,
Harsha

**Comment by danlamanna** [comment]
Awesome.

I started creating a document for what an ImageSpace plugin needs to look like but never finished it, I included it below. It's a little sloppy, and I'm unsure if certain parts of how it's setup are going to be permanently - but it should get you started. Feel free to setup a WIP PR to share code/ask for any assistance.

# Creating a search endpoint in Girder

## Must return results that look similar to the Solr index ImageSpace is using

To do so, a JSON object with 2 keys are required:

numFound A numFound key must be returned with the number of total results. If the collection supports pagination then this value must be the total number of results among all pages, if it doesn’t then just return the length of documents.

docs A docs key must be returned with the JSON objects representing each Solr document.

## The collection must be able to pass classifications to python rest end points

Since classifications are part of ImageSpace, the endpoint must be able to accept a list of classifications (strings such as `smqtk_hg_revolver_d_md`) that it can further narrow results by.

If given a list of paths, a function exists in the core ImageSpace plugin called `solr_documents_from_paths` which can take a list of classifications to narrow results down by as well. This also performs the querying in chunks to avoid sending too much data.

**Comment by harsham05** [comment]
Thank you so much @danlamanna 

This is super helpful :)

**Comment by harsham05** [comment]
@danlamanna 
After building Girder with symbolic links created for CMU, Columbia, etc, local Deployment fetches the ImageSpace application, but how to navigate back to girder web-app to enable to each plugin (CMU, Columbia) ?

Also, I am unable to get ImageSearch to leverage our Solr Weapons index despite setting the env variables?

![imagespace deployment](https://cloud.githubusercontent.com/assets/8755540/12471026/532cd122-bfae-11e5-991f-ed565349dd0a.png)

**Comment by danlamanna** [comment]
The Girder web app should be available at `/girder`, so for you it looks like http://localhost:8095/girder. The first user created will have admin access to the plugins panel.

As for the environment variables, try checking the `~/pilot_atf_imagespace/atf_source.env` file on the dyndns machine for our current setup. If you don't have access I can email it to you.

**Comment by harsham05** [comment]
Thank you @danlamanna 
Are you available to chat over Glip or Hangouts?
I have sent you an invite

**Comment by chrismattmann** [comment]
@smadha took care of this, all done! it's part of videospace_tika
