### ISSUE TITLE
Need to show how images are similar

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/image_space#13]
We currently have 3 or 4 ways of identifying images as similar when we search for similar images from a given image. We need to find a way to make it obvious how it is that these images are similar.

This is not an immediate problem that needs to be solved, but it should be solved before we enter a pilot.

When an image comes up in a list of similar images, it would be helpful to know how each one is similar. Do they share common EXIF data? Is it through the image histogram? Is there OCR'd text? Some of these can be considered soft connections and others hard. Analysts will want to know these connections.

Potentially, the expansion of the Image Size and Serial Number capabilities in the left side bar could help with this also - a sort of faceted search that would narrow the manner in which the shown images are connected. This is just a brainstormed thought - so after further consideration, it may not be a good answer, but I'm sharing it here anyway.

**Comment by jeffbaumes** [comment]
Thanks for the thoughts. It is normally explicit what the search is when it is from a faceting (clicking on scatterplot, bar chart, or magnifying glass or plus in the details window) - due to the "AND key:value" added to the search bar. It is true that you often lose the context (image) from which the faceted search was made which is not ideal.

As for the "Find similar images" button in the details window - currently that is entirely distinct from faceting. Those matches are always similar in histogram and histogram alone. These matches are found outside the Solr database by another means, then a Solr query is constructed that picks out the specific similar images. I could at least make that button function clearer by calling it "Find similar-looking images" or "Find images with similar color histograms". In the future it would be good if this button truly looked across both computer vision features and Tika metadata features in a unified distance metric, but this is not where we are today.

**Comment by wmburke** [comment]
Thank you, Jeff. That helps my understanding a great deal. Let's not 
change anything right now and see what sort of feedback we get to help 
guide us on this.
