### ISSUE TITLE
Landing Page CSS and other changes

### ISSUE THREAD

**Issue by lawongsta** [memex-explorer/image_space#89]
![simple landing page](https://cloud.githubusercontent.com/assets/12855060/11886462/2bcff4c2-a4df-11e5-8e38-91b365a9d9a8.png)

CSS changes:
Adding padding and extending search box

.im-search-form{
width:80%;
}

div.form-group.im-search-form-group{
padding-top: 10px;
padding-bottom: 5px;
}

Change text to: Enter search term or drop an image
Login/ Register: Why do we need users to login before dropping an image? Why can't you drop an image initially?

Can we remove the left hand side bar? 
I don't think users will need to blur images of weapons. Also, there was some feedback from the SUG reports that said the serial number and image size distribution graphs were not helpful. I do not think we need to include for the pilot.

**Comment by jeffbaumes** [comment]
The left bar is the only place user-supplied images and saved images appear. I believe these should be visible on the main page as well as the results page.

Images must be uploaded to the server and served on a URL in order to be used by external indices like Columbia and CMU. This is most easily accomplished in a user's upload space on the server, which also ensures their images are kept private by default, and makes them available. If a user is not logged in, that image could be public, and the image would be lost if the user refreshes the page or closes the tab.

All that said, I agree that a no-login upload could be a good feature that is possible to implement. I'll put that as a separate issue that we may decide to address, but for now I won't put it in the SUG milestone.

**Comment by wmburke** [comment]
How about we remove everything else from the left side bar (blur/unblur as unnecessary in this domain -- I like your settings fix on this one; the serial number and image size distributions), and have the sidebar show up only if there are saved images contained there -- otherwise, just display:none. This would present a really clean interface for first time users, but then make all saved images easily available from the main search page for returning users.

**Comment by jeffbaumes** [comment]
Yes @wmburke that could work.

**Comment by jeffbaumes** [comment]
I think we are close enough to this vision to close out this issue.
